# Generated by Django 3.2.12 on 2022-09-11 18:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Privilege', '0003_alter_privilegeuser_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='privilegemessage',
            name='privilege_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Privilege.privilegeuser'),
        ),
    ]
